from discord.ext import commands
import discord
from discord import app_commands

class GenerateInviteCog(commands.Cog):
    def __init__(self, bot:commands.bot):
        self.bot = bot

    @app_commands.command(description = "Generates an invite link to this discord server.")
    async def generate_invite(self, interaction: discord.Interaction):
        inviter = interaction.user

        invitelink = await interaction.channel.create_invite(max_age = 90, max_uses=1, unique=True)

        await interaction.response.send_message("Invite link has been generated by " + inviter.mention + ".")
        await interaction.channel.send(invitelink)

async def setup(bot: commands.Bot):
    await bot.add_cog(GenerateInviteCog(bot))